apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: front-end
      app.kubernetes.io/component: front-end
      app.kubernetes.io/instance: front-end
    name: front-end
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: front-end
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: front-end
      spec:
       containers:
        - image: 'quay.io/cpranava0/flask-redirect:main'
          name: front-end
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          env:
          - name: BASE_URL
            value: http://back-end.test.svc.clusterset.local:5000
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
kind: List
metadata: {}

